### ISSUE TITLE
Download không hết

### ISSUE THREAD

**Issue by nhhuayt** [NguyenKhong/Download_Edumall_beta#1]
Bạn cho mình hỏi:
Như khóa học của mình là: Thiet ke va sua chua cac loai nguon xung
Trong đó bài 25 thì xem trên web là hơn 4 phút, nhưng down về thì chỉ được hơn 1 phút.
Mà chỉ bị lỗi bài 25 thôi. Không biết là do sao vậy bạn ?

**Comment by NguyenKhong** [comment]
Nếu bạn tin tưởng giao tài khoản cho mình kiểm tra thì có thể liên hệ qua fb: https://www.facebook.com/profile.php?id=100009326128280
Vì phần mềm này phân tích html ra url video để tải về nên chả rõ nó có sai xót chỗ nào không nữa. Chắc phải cập nhật lại chế độ debug.
