### ISSUE TITLE
Kính gửi a NguyenKhong

### ISSUE THREAD

**Issue by huytranxd2016** [NguyenKhong/Download_Edumall_beta#4]
A ơi bản download edumall mới nhất bị lỗi rồi ạ. A fix lỗi giúp e với ạ. Nó báo lỗi vầy nè anh.
2019-10-17 21:05:00,829 GetCourses WARNING: Loi Phan tich khoa hoc

**Comment by NguyenKhong** [comment]
Chào bạn lâu rồi không vào edumall nên không kiểm tra. Bản cập nhật mới nhất ngày 12/11/2019 đã có.

**Comment by huytranxd2016** [comment]
Cảm ơn bạn.

Vào 19:03, T.3, 12 Th11, 2019 NguyenKhong <notifications@github.com> đã
viết:
