### ISSUE TITLE
Phần mềm không hoạt động

### ISSUE THREAD

**Issue by mrducdc** [NguyenKhong/Download_Edumall_beta#5]
Tại thời điểm ngày 31/10/2019 phần mềm hiển thị cảnh báo và không download đc

**Comment by NguyenKhong** [comment]
Chào bạn lâu rồi không vào edumall nên không kiểm tra. Bản cập nhật mới nhất ngày 12/11/2019 đã có.

**Comment by mrducdc** [comment]
cảm ơn bạn ! mình đã tự down dc bằng ffmkeg và video download helper rùi ạ.
Phần mềm của bạn có down dc từ udemy.com.vn ko ạ

**Comment by NguyenKhong** [comment]
Tất nhiên là không rồi. Với udemy bạn có thể dùng [youtube-dl](https://github.com/ytdl-org/youtube-dl).

**Comment by mrducdc** [comment]
udemy.com.vn nó khác bạn ạ, cái kia mình làm đc rồi
